openapi: 3.0.0
info:
  title: my-personal-portfolio-project
  version: 0.1
paths:
  /{url+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eeccu0sd9fl6tf60bd
        tag: $latest
      parameters:
      - explode: false
        in: path
        name: url
        required: false
        style: simple
